libemu: update documentation

diff --git a/lib/libemu b/lib/libemu
--- a/lib/libemu
+++ b/lib/libemu
@@ -1,10 +1,14 @@
 #!/bin/bash
 
-# emu version number
+#### VARIABLES
+
 export EMU_VERSION="0.0.1"
 
-# exit code for command not found error
+# exit codes
+export EMU_RETURN_ERROR=1
 export EMU_RETURN_COMMAND_NOT_FOUND=127
+
+#### PRIVATE
 
 _emu_echo ()
 {
@@ -26,9 +30,11 @@ _emu_echo ()
     echo -n $emu_prefix_color >&$stream
 }
 
+#### PUBLIC
+
 # print a message
-#  @param $1 msg
-#  @var EMU_ECHO_PREFIX (optional) output prefix
+#  @param $1                         msg
+#  @var   EMU_ECHO_PREFIX (optional) output prefix
 emu_echo ()
 {
     local msg="$1"
@@ -43,8 +49,8 @@ emu_echo ()
 }
 
 # print a warning message
-#  @param $1 msg
-#  @var EMU_ECHO_PREFIX (optional) output prefix
+#  @param $1                         msg
+#  @var   EMU_ECHO_PREFIX (optional) output prefix
 emu_warning ()
 {
     local msg="$1"
@@ -59,8 +65,8 @@ emu_warning ()
 }
 
 # print an error message
-#  @param $1 msg
-#  @var EMU_ECHO_PREFIX (optional) output prefix
+#  @param $1                         msg
+#  @var   EMU_ECHO_PREFIX (optional) output prefix
 emu_error ()
 {
     local msg="$1"
@@ -74,6 +80,7 @@ emu_error ()
     return 0
 }
 
+# TODO: implement
 get_source_dir ()
 {
     ls
@@ -108,13 +115,12 @@ exit_with_error ()
             unlock_dir "$sink"
         fi
     done
-    exit 1
+    exit $EMU_RETURN_ERROR
 }
 
-# Check for write permissions
-#
-# @var $SCRIPT (optional) echo prefix.
-# @param $1 path to the directory.
+# check for write permissions
+#  @var   $SCRIPT (optional) echo prefix
+#  @param $1                 path to the directory
 exit_if_no_dir_permissions ()
 {
     local dir="$1"
@@ -141,9 +147,8 @@ exit_if_no_dir_permissions ()
     fi
 }
 
-# Execute each in a list of executables.
-#
-# @param $1 a list of absolute paths to files.
+# execute each in a list of executables
+#  @param $1 a list of absolute paths to files
 exec_list ()
 {
     local list="$1"
@@ -154,57 +159,51 @@ exec_list ()
     done
 }
 
-# Execute pre-execution hooks.
-#
-# @param $1 Path to source directory.
+# execute pre-execution hooks
+#  @param $1 Path to source directory
 pre_exec_hooks ()
 {
     HOOKS=$(find "$1/.emu/hooks/exec/" -name '*.pre' 2>/dev/null)
     exec_list $HOOKS
 }
 
-# Execute post-execution hooks.
-#
-# @param $1 Path to source directory.
+# execute post-execution hooks
+#  @param $1 Path to source directory
 post_exec_hooks ()
 {
     HOOKS=$(find "$1/.emu/hooks/exec/" -name '*.post' 2>/dev/null)
     exec_list $HOOKS
 }
 
-# Execute error condition hooks.
-#
-# @param $1 Path to source directory.
+# execute error condition hooks
+#  @param $1 Path to source directory
 error_exec_hooks ()
 {
     HOOKS=$(find "$1/.emu/hooks/exec/" -name '*.error' 2>/dev/null)
     exec_list $HOOKS
 }
 
-# Return the number of snapshots in sink.
-#
-# @param $1 Path to sink directory.
+# return the number of snapshots in sink
+#  @param $1 Path to sink directory
 sink_snapshot_count ()
 {
     echo "$(ls -l "$1/.emu/trees" | wc -l)"
 }
 
-# Return the max number of snapshots for sink.
-#
-# @param $1 Path to sink directory.
+# return the max number of snapshots for sink
+#  @param $1 Path to sink directory
 sink_max_snapshots ()
 {
     echo "$(cat $1/.emu/config/SNAPSHOT-COUNT)"
 }
 
-# Check and block directory. If the directory is already locked, it will block
-# and poll periodically until free.
-#
-# @param $1 Path to directory to block on.
-# @var BLOCK_SLEEP_TIME Time to sleep between block attempts (s).
-# @var BLOCK_COUNTER Numeric Variable which must be initialised to 0.
-# @var BLOCK_COUNTER_MAX Maximum number of attempts before failing, or -1 to
-#                        continue indefinitely.
+# check and block directory. If the directory is already locked, it will block
+# and poll periodically until free
+#  @param $1                Path to directory to block on
+#  @var   BLOCK_SLEEP_TIME  Time to sleep between block attempts (s)
+#  @var   BLOCK_COUNTER     Numeric Variable which must be initialised to 0
+#  @var   BLOCK_COUNTER_MAX Maximum number of attempts before failing, or -1 to
+#                           continue indefinitely
 block_until_dir_free ()
 {
     if [[ -f "$1/.emu/LOCK" ]]
@@ -220,11 +219,11 @@ block_until_dir_free ()
             fi
         fi
 
-        # Print the PID of blocking process.
+        # print the PID of blocking process
         BLOCK_PID=$(cat "$1/.emu/LOCK" | grep PID | sed -r 's/PID: +//')
         echo -en "\r$1 blocking on process: $BLOCK_PID "
 
-        # Print status of blocking process.
+        # print status of blocking process
         BLOCK_STATUS=$(ps -p "$BLOCK_PID")
         if (( $? ))
         then
@@ -237,9 +236,8 @@ block_until_dir_free ()
     fi
 }
 
-# Lock the specified directory.
-#
-# @param $1 Path to the directory to lock.
+# lock the specified directory
+#  @param $1 Path to the directory to lock
 lock_dir ()
 {
     BLOCK_SLEEP_TIME=1
@@ -250,9 +248,8 @@ lock_dir ()
     echo -e "DATE: $(date)\nPID:  $$" > "$1/.emu/LOCK"
 }
 
-# Remove the lock on source directory.
-#
-# @param $1 Path to directory to lock.
+# remove the lock on source directory
+#  @param $1 Path to directory to lock
 unlock_dir ()
 {
     LOCK=$(cat "$1/.emu/LOCK" 2> /dev/null)
@@ -270,6 +267,7 @@ unlock_dir ()
     fi
 }
 
+# TODO: documentation
 print_sink_details ()
 {
     SINK_PATH="$(cat $SOURCE_DIR/.emu/sinks/$1)"
@@ -286,9 +284,8 @@ cat <<EOF | less
 EOF
 }
 
-# Generate a 32 digit hash of a directory.
-#
-# @param $1 Path to directory.
+# generate a 32 digit hash of a directory
+#  @param $1 Path to directory
 hash_directory ()
 {
     pushd . > /dev/null
@@ -300,9 +297,8 @@ hash_directory ()
     echo $HASH
 }
 
-# Calculate and compare the snapshot hash against the node hash.
-#
-# @param $1 Path to snapshot.
+# calculate and compare the snapshot hash against the node hash
+#  @param $1 Path to snapshot
 verify_node ()
 {
     NODE=$(basename "$1")
@@ -320,11 +316,10 @@ verify_node ()
     exit_with_error "$SOURCE_DIR"
 }
 
-# Lookup info from an emu node
-#
-# @param $1 Node path
-# @param $2 Key
-# @return Value for key, or empty string if not found
+# lookup info from an emu node
+#  @param  $1 Node path
+#  @param  $2 Key
+#  @return    Value for key, or empty string if not found
 lookup_node_key ()
 {
     echo "$(cat $1 2>/dev/null | grep $2 | sed -r 's/'$2' +(.*)/\1/')"
